### ISSUE TITLE
Dome is now less responsive to manual input.  

### ISSUE THREAD

**Issue by Maxstang289** [reeltwo/DomeControlFirmware32#17]
The scaling is being applied to the manual input to the dome. I suspect this is a feature and not a bug?  The result is that out of the box, the dome feels far less responsive, but I'll mess with the settings and see if I can get it where I want it.  Turning the scaling of greatly improves the responsiveness of the manual input and of the stored sequences.

**Comment by rimim** [comment]
Manual input is no longer affected by scaling.
