### ISSUE TITLE
Target Speed Percentage still ignores Global Max Speed Varriable

### ISSUE THREAD

**Issue by Maxstang289** [reeltwo/DomeControlFirmware32#18]
Once again... this could be a feature, not a bug.  It appears the TARGETMAXSPEED ignores the DPMAXSPEED setting and is an absolute seek speed.  That's fine... except we need to note it and not set the default to 100.    Otherwise all sequences without specified speeds run the risk of moving the dome faster than the programmer expects... as they've already set a max speed for the "DOME", "SEEK" and "HOME".  I'm wondering if it would be smarter to have the DPMAXSPEED be a global setting that cannot be exceeded by any of the other settings.

**Comment by rimim** [comment]
DPMAXSPEED is now respected for all operations.
